import WdtClient
import json
### 创建原始订单 原始订单推送接口
t =  WdtClient.WdtClient('appkey_market_test', 'AFX2fD4pt', 'haijun', 'https://openapitest.huice.com/openapi/')
trade_list = []
order_list = []
order_1 = {}
order_1.update({"oid": 'ghsTest121101'})
order_1.update({"num": 1})
order_1.update({"price": 12})
order_1.update({"status": 30})
order_1.update({"refund_status": 0})
order_1.update({"goods_id": '18344'})
order_1.update({"spec_id": '18656'})
order_1.update({"goods_no": 'ghs2'})
order_1.update({"goods_name": 'ghs201812070212123'})
order_1.update({"spec_no": 'ghs201812070212123'})
order_1.update({"spec_name": 'Chs1231110'})
order_1.update({"discount": 0})
order_1.update({"adjust_amount": 0})
order_1.update({"share_discount": 0})
order_list.append(order_1)
### order_list 可以包含多个 明细 举例可以包含order_1 ... oid 必须保证 唯一
order_2 = {}
order_2.update({"oid": 'ghsTest121102'})
order_2.update({"num": 1})
order_2.update({"price": 12})
order_2.update({"status": 30})
order_2.update({"refund_status": 0})
order_2.update({"goods_id": '18344'})
order_2.update({"spec_id": '18656'})
order_2.update({"goods_no": 'ghs2'})
order_2.update({"goods_name": 'Chs1231110货品名称'})
order_2.update({"spec_no": 'ghs201812070212123'})
order_2.update({"spec_name": 'Chs1231110'})
order_2.update({"discount": 0})
order_2.update({"adjust_amount": 0})
order_2.update({"share_discount": 0})
order_list.append(order_2)
trade_1 = {}
trade_1.update({"tid": 'AT201812110002'})
trade_1.update({"trade_status": 20})
trade_1.update({"pay_status": '1'})
trade_1.update({"delivery_term": 2})
trade_1.update({"trade_time": '2018-12-11 14:21:00'})
trade_1.update({"buyer_nick": '三国杀'})
trade_1.update({"receiver_mobile": '17611451203'})
trade_1.update({"receiver_name": '亚历山大'})
trade_1.update({"receiver_province": '河南省'})
trade_1.update({"receiver_city": '周口市'})
trade_1.update({"receiver_district": '川汇区'})
trade_1.update({"receiver_address": '123'})
trade_1.update({"logistics_type": 4})
trade_1.update({"post_amount": 12})
trade_1.update({"cod_amount": 2})
trade_1.update({"ext_cod_fee": 0})
trade_1.update({"other_amount": 1})
trade_1.update({"paid": 0})
trade_1.update({"order_list": order_list})
trade_list.append(trade_1)
# del(trade_list[0])
jsonArr = json.dumps(trade_list, ensure_ascii=False)
params = {}
params.update({"shop_id": '23'})
params.update({"trade_list": jsonArr})
response = t.execute("trade_push.php", params)
print(response)
